### ISSUE TITLE
Odd behavior: Verbose mode seems to indicate that state is always set to 2 no matter what config says

### ISSUE THREAD

**Issue by Reapette** [fitnr/twitter_markov#12] opened 2018-03-01 17:24 UTC
Config has in it

**state_size: 4**

But when run, verbose output says

**twitter_markov.py 104: setting up models (state_size=2)**

what has gone wrong?

**Comment by fitnr** [comment] 2018-03-01 18:54
What's the setup of your config file? You can remove any extra data like keys before pasting in.

**Comment by Reapette** [comment] 2018-03-01 22:25
apps:
    REDACTED:

        # From dev.twitter.com
        consumer_key: 'REDACTED'
        consumer_secret: 'REDACTED'

users:
    REDACTED:
        # oauth with twitter to get these
        key: 'REDACTED-REDACTED'
        secret: 'REDACTED'

        # this should match one of the apps above
        app: RealJudaldButtrump

        # If your bot is based on another account, the screen name of that account
        parent: REDACTED

        # Location of a text file, with one tweet (or other sentence) per line
        # This can also be set on the command line.
        # This can be a single item or a list
        #
        corpus: /user0/REDACTED-1.txt

        # How many tweets should we check to make sure we're not repeating something we already tweeted?
        checkback: 22

        # This determines how long of a phrase the markov chain be working with.
        # Higher values are slower and hew closer to the corpus
        # Lower values are faster and more oddball
        #
        state_size: 4

        # Words to never tweet
        # These will be added to a built-in blacklist, taken from https://github.com/dariusk/wordfilter
        #
        blacklist:
            - REDACTED

        # With these set to True, we won't tweet these types or learn them from its parent
        #
        no_retweets: False
        no_replies: False

        # With these set, these types of tweets won't be tweeted
        # They will still be fed into the corpus, they will just
        # be filtered out of results
        #
        no_hashtags: False
        no_urls: True
        no_mentions: False
        # Symbols are stock ticker abbreviations like $APPL
        no_symbols: False

        # With these set, the text will be stripped of these entities before being fed to the brain
        # For instance, if filter_hashtags is set,
        # "What's Going On #lemonheads" will be fed to the brain as:
        # ""What's Going On"
        # Take care. Changing the corpus in this way can lead to strange results.
        #
        filter_hashtags: False
        filter_media: False
        filter_urls: False
        filter_mentions: False
        filter_symbols: False

        # By default, wordfilter is applied to the parent's tweets.
        filter_parent_badwords: False

**Comment by Reapette** [comment] 2018-03-01 22:40
BTW, specifying --state-size=4 from command line works!

**Comment by fitnr** [comment] 2018-03-06 02:18
I can't reproduce this. I'm closing pending more reports.

**Closed by fitnr** 2018-03-06 02:18 UTC
